baseURL: "https://mirhasshugo.netlify.app/""
languageCode: en-us
title: Mir Hass
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: John Doe - All rights reserved
enableEmoji: yes
publishDir: docs
params:
  author: Mir Hass
    description: My R Musings.
    name: Mir Hass
    thumbnail: /images/author.png
  description: the clean blog!
  index:
    alertbar: no
    mdtext: "\r\nCurrently trying to get this blog running, still don't know what
      the blog will be about!\\\r\n**This textblock is a demonstration of the mdtext-param.**\\\r\n###
      This is a markdown heading\r\n"
    picture: /images/author.png
    subtitle: I'm trying learn Data Science with R! 
    title: John Doe
  logo: /images/logo.png
  social:
    github: <mirmubarak>
    instagram: <username>
    linkedin: <username>
    medium: <username>
    twitter: <@twitter>
    xing: <username>
menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog
      weight: 100
    - identifier: about
      name: About Me
      url: /
      weight: 200
    - identifier: imprint
      name: Imprint
      url: /static/imprint
      weight: 200
